#!/bin/bash -l

#SBATCH --job-name=makelist
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --partition=short-cpu

# ========================= get_unique_pairs.sh =========================
#
#  DESCRIPTION: Gets unique pairs of genes and splice types. (Example:
#          AAEL0012345 with A3SS will only show up once) Creates a CSV
#          with each gene/splicetype pair. Can also be run with sbatch,
#          but it shouldn't be terribly slow.
#
#  USAGE: get_unique_pairs.sh $1 $2
#        Argument 1 - CSV to get unique pairs from. Should be one of the CSVs
#                        generated by make_sorted_lists.sh.
#        Argument 2 - Name/path of the new CSV file to generate, containing
#                        the unique pairs.
#
#  OUTPUT: CSV file with each unique gene/splicetype pair.
#
# =======================================================================

# Set up inputs
csv=$1
outfile=$2

# Make new CSV to contain the unique pair data.
touch $outfile
printf "" > $outfile

# Loop over each line in the input CSV, skipping the first... (first line is a header)
isfirst=1
while read line; do
	if [[ $isfirst -ne 1 ]]; then
    # Get the gene and splice type...
    gene=$(echo $line | cut -d',' -f1)
    splice=$(echo $line | cut -d',' -f4)
    
    # If the output CSV doesn't already contain that gene/splicetype pair, add it.
		if ! grep -q "^${gene},[^,]*,[^,]*,${splice}" $outfile; then
			echo $line >> $outfile
		fi

	else
		isfirst=0
	fi
done < $csv

# Add header line.
sed -i '1iGeneID,GeneName,Function,SpliceType,Description,GeneLocation' $outfile