#!/usr/bin/env bash
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --job-name=bwcompare_array
#SBATCH --partition=short-cpu
#SBATCH --output=%x.%j.log # gives jobname.ID.log
# Available partitions
# day-long-cpu
# day-long-gpu
# day-long-highmem
# exp-gpu
# short-cpu*
# short-gpu
# short-highmem
# week-long-cpu
# week-long-gpu
# week-long-highmem

# ================= 03.3_bwCompareArray.sh ===================
#
#  DESCRIPTION: A Slurm array script to run the bigwigCompare function
#            for all the bigwigs in the supplied comparison file.
#
#  USAGE: sbatch --array=0-(number of comparisons minus 1) 03.3_bwCompareArray.sh $1 $2
#
#  INPUTS: $1 - The directory the target bigwigs are in.
#
#          $2 - Path to the file containing bigwig comparisons to be made.
#              They must list file names relative without any directories
#              preceding them. Thus, they must be in the directory described
#              by input $1. This file is generated by SICC_array.sh.
#
#              Comparison data is written using the following rules:
#                    
#                      1. Each line is comma-separated, with the input at the end:
#
#                          Treatment.bam,Input.bam
#
#                      2. You can compare multiple treatments to the same control
#                          like so. They will each produce a different bigwig:
#
#                          Treatment_Ac.bam,Treatment_Me.bam,Treatment_Ago2.bam,Input.bam
#
#                      3. Example line:
#
#                          BF-d3-merged_me.bam,BF-d3-merged_ac.bam,BF-d3-merged_input.bam
#
#  OUTPUT: Bigwig (.bw) files in the same directory as the bams
#
# ============================================================

source activate base
conda init
conda activate deeptools_kernel

cd $1

mkdir bw_compare
mkdir dt_tmp
export TMPDIR="$(pwd)/dt_tmp"

compnum=0
while IFS=',' read -r -a line; do
	for ((i=0; i < ${#line[@]}-1; i++)); do
		if [ $SLURM_ARRAY_TASK_ID -eq $compnum ]; then
			treat=${line[i]}
			input=${line[-1]}
			treat=${treat/.bam/.bw}
			input=${input/.bam/.bw}
			bigwigCompare -b1 $treat -b2 $input -o ./bw_compare/compare_$treat --binSize 10 --numberOfProcessors 4 --operation subtract
			compnum=$((compnum + 1))
		fi
	compnum=$((compnum + 1))
	done
done < $2

